---
- name: update webserver
  hosts: webservers
  remote_user: osboxes
  become: yes
  become_user: root
  tasks:
    - name: ensure wireshark is at the latest version
      yum:
        name: wireshark
        state: latest

    - name: Create a new directory named New-Dir
      file:
       path: ~/New-Dir
       state: directory

    - name: Create a file named new-file
      file:
       path: ~/New-Dir/new-file
       state: touch

    - name: Change time zone to Africa/lagos
      timezone:
         name: Africa/Lagos
