#[nfs]
#172.31.84.45 ansible_ssh_user='ec2-user'

[webservers]
192.168.56.111 ansible_ssh_user='osboxes'
#172.31.88.181 ansible_ssh_user='ec2-user'

#[db]
#172.31.94.226 ansible_ssh_user='ec2-user'

#[lb]
#172.31.93.97 ansible_ssh_user='ubuntu'
